### ISSUE TITLE
Can I replace that heart icon with other emojis?

### ISSUE THREAD

**Issue by isaanyoha** [JohnF17/heart_overlay#1]
Thank you for this awesome feature.

Can I replace that heart icon with other emojis?

**Comment by JohnF17** [comment]
Hello @isaanyoha, You're welcome! and I'm glad you're enjoying the package.

You can replace the heart icon with other icons using the following code:
```
HeartOverlay(
  icon: const Icon(
    Icons.add, // Replace with the desired emoji icon
    color: Colors.purple,
    size: 100,
  ),
),
```
As of my last update, directly using widgets (such as the `Text` widget _to put text or emojis_) is not supported yet, but you can use the approach above to replace the heart icon with an icon of your choice.

For further updates and changes, make sure to check the [CHANGELOG here](https://github.com/JohnF17/heart_overlay/blob/master/CHANGELOG.md), i'll be sure to add widget support soon as described on the `[Next]` section in the change log.
Hope this answers your question! ✌️

**Comment by JohnF17** [comment]
But don't you worry @isaanyoha, i've now just released [`HeartOverlay Version: 1.3.0`](https://pub.dev/packages/heart_overlay)
It has support for displaying any kind of widget instead of just `icon`s, and that includes `Text` to show your emojis.

```dart
 HeartOverlay(
    icon: const Text('✌️'),
    size: 60,
    verticalOffset: 20,  // Vertical Offset from tap position
    horizontalOffset: -10,  // Horizontal Offset from tap position
    duration: Duration(milliseconds: 800), // Icon to stay on screen duration 
    tapDownType: TapDownType.single, // The animation trigger type
    onPressed: (numberOfHearts) {
        // Do something with the number of hearts shown or do something whenever the icon appears
    },
    child: Image.asset('assets/image.png'), // Overlay container background
  ),
```

NOTE: please be aware that you might have to fiddle with the _vertical_ and _horizontal_ offsets to precisely align the widget to its tap position.

Make sure to close the issue if the issue has been resolved✌️ and check out the [CHANGELOG](https://github.com/JohnF17/heart_overlay/blob/master/CHANGELOG.md) for additional details and know more about the next release.

**Comment by isaanyoha** [comment]
Thanks for the reply!

Also, can we set the package in such a way that we can:
-  enable/disable touch overlay *area* (letting only the button to be clickable)?
-  click the overlay button automatically based on a bool condition?

I am developing a chat app where of personA taps a heart (or any other emoji) icon on his device, and the condition is sent personB's device which, the sent condition now in personB's device, will cause the click of the heart_overlay button thereby triggering the animation of the heart_overlay widget & showing the desired emoji icon

**Comment by isaanyoha** [comment]
Thanks for the reply and update!
